version: 0.2

env:
  variables:
    USER: jmdevuser
    BUCKET_NAME: jm-polly-bucket-5513
    AWS_REGION: "us-east-2"
  parameter-store:
    TOKEN: ssp_github_pat
phases:
  install:
    commands:
      - echo "Installation of Pre-build tools.."
      - wget https://releases.hashicorp.com/terraform/1.1.6/terraform_1.1.6_linux_amd64.zip
      - unzip terraform_1.1.6_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_1.1.6_linux_amd64.zip
  pre_build:
    commands:
      - echo PreBuild started ....
  build:
    commands:
      - echo "Build started on `date` "
      - mkdir /tmp/plan
      - terraform init
      - terraform plan -out=/tmp/plan/plan-out -no-color 2>&1 | tee /tmp/plan/describe-plan
      - aws s3 cp /tmp/plan/ s3://$BUCKET_NAME/$CODEBUILD_SOURCE_VERSION/plan/ --recursive
      #- sh /opt/github-callback.sh "$(cat /tmp/plan/describe-plan)"
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
