version: 0.2

env:
  variables:
    USER: jmdevuser
    BUCKET_NAME: jm-polly-bucket-5513
    AWS_REGION: "us-east-2"
  parameter-store:
    TOKEN: ssp_github_pat
phases:
  install:
    commands:
      - echo "Installation of Pre-build tools.."
      - pip install --upgrade --quiet boto3
      - pip install --upgrade --quiet awscli botocore
      - wget https://releases.hashicorp.com/terraform/1.1.6/terraform_1.1.6_linux_amd64.zip
      - unzip terraform_1.1.6_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_1.1.6_linux_amd64.zip
  pre_build:
    commands:
      - echo PreBuild started ....
  build:
    commands:
      - echo "Build started on `date` "
      - cd ./examples/eks-cluster-with-new-vpc
      - mkdir /tmp/plan
      - terraform init
      - terraform apply --auto-approve
      -  terraform destroy --auto-approve
  post_build:
    commands:
      - terraform destroy --auto-approve

